baseURL = "https://kangmin-lee.github.io/"
languageCode = "ko-kr"
title = "Jihee"
theme = "gallery"

[params]
  title = "Interior Design Style Guide"
  description = """
고객님의 취향을 파악하기 위한 인테리어 스타일 가이드입니다.

선택해 주신 스타일과 이미지를 바탕으로 3D 시안에 맞춤 디자인을 반영해 드립니다.
"""
  [params.author]
    email = "user@example.com"
    name = "Your Name"